### ISSUE TITLE
поля картинок

### ISSUE THREAD

**Issue by AndreyMkr** [andreymukha/mes_board#1]
Добавить больше полей для картинок. Очень мало.

http://joxi.ru/Rmzgwbdu41bP2O

**Comment by andreymukha** [comment]
Точнее, сколько?

**Comment by AndreyMkr** [comment]
10-15.

**Comment by andreymukha** [comment]
Добавить поля легко, но ты уверен, что столько необходимо?)))

**Comment by AndreyMkr** [comment]
а как можно продать квартиру по 3м картинкам? если у меня 4 комнаты 2 ванны и туалета с кухнями + прихожая и котэ

**Comment by andreymukha** [comment]
Проверяй! :)
