### ISSUE TITLE
отличие алертов схожих полей

### ISSUE THREAD

**Issue by AndreyMkr** [andreymukha/mes_board#5]
Если в полях "Дополнительное изображение" насовать не допустимые файлы, то выводится алерт http://joxi.ru/bmoOw0McYVg9my
тоесть алерт отличается от алерта основного изображение.
было бы неплохо чтобы в алерте выводилось в каком поле изображения пытаются всунуть не допустимый файл.

**Comment by andreymukha** [comment]
Проверяй по поводу допустимых типов файлов.
По поводу какое именно изображение, то там цифра стоит, к какому изображению относится ошибка http://joxi.ru/L21jpdMh9k6eAX

**Comment by AndreyMkr** [comment]
не зависимо в каком поле изображения не верный тип файла, выводится одно и тоже http://joxi.ru/L21jpdMh9k6eAX

**Comment by AndreyMkr** [comment]
в третьем дополнительном изображении добавил не допустимый файл, сообщение что во 2м http://joxi.ru/8An0wpghp5JZmO

**Comment by andreymukha** [comment]
Проверяй
