### ISSUE TITLE
поле Цена

### ISSUE THREAD

**Issue by AndreyMkr** [andreymukha/mes_board#8]
если в поле цена написать "2?2", или другой знак, то выведет все цифры до знака "?".
надо запретить ввод символов в это поле.
для примера http://стройкасса.рф/activate_virtual_card, выбери "мой город", любой город.
в полях ФИО попробуй ввести символы либо латиницу.
так же исключить возможность добавлять объявление со стоимостью "0".

**Comment by andreymukha** [comment]
Это хорошо при помощи JS делать, к этому ближе к концу приступлю

**Comment by andreymukha** [comment]
Готово
